### PR TITLE
Adding confirmation when delete iklan and updating layout

### PR DESCRIPTION
**Pull request by syaifuddinzuhri**
Adding confirmation when delete iklan and updating layout

Screenshot from 2020-11-03 20-48-06

Screenshot from 2020-11-03 20-48-11

### CODE REVIEW

**Comment by masaditya** [comment]
LGTM! :metal:

**Comment by masaditya** [comment]
> Adding confirmation when delete iklan and updating layout
> 
> Screenshot from 2020-11-03 20-48-06
> 
> Screenshot from 2020-11-03 20-48-11

eh koyoke kok layout sing atas urung ke-update yo ndek deployment e? lali di commit a? :v @syaifuddinzuhri

**Comment by masaditya** [comment]
ndek deploy ne search dan add button e ilang wkwkw

**Comment by syaifuddinzuhri** [comment]
> ndek deploy ne search dan add button e ilang wkwkw

belum aku commit keknya...wkwk

**Pull request merged**
